### ISSUE TITLE
[BUG] Select properties not found

### ISSUE THREAD

**Issue by radikris** [csandman/chakra-react-select#10]
Hey!

Thanks for this awesome lib, but recently I had a problem with it:

![image](https://user-images.githubusercontent.com/55052220/138062773-b1ff5632-e244-4793-9607-659485d80804.png)

I imported the "import { Select, CreatableSelect } from "chakra-react-select";"
and still it says that these properties (neither ismulti, nor options) are available in the props:

![image](https://user-images.githubusercontent.com/55052220/138063027-8f3cfc26-de1b-4d16-ae74-e0452c35e956.png)
![image](https://user-images.githubusercontent.com/55052220/138063261-bd30dc0d-77e5-4295-9530-16243daf7771.png)

Can you help me out what is going on? I just tried to check the examples on the site, but not working:/
(Followed these examples: https://codesandbox.io/s/chakra-react-select-demo-65ohb?file=/example.js)

**Comment by Patrascu-Lucian** [comment]
I don't get this error: https://codesandbox.io/s/chakra-react-select-ts-test-z131f?file=/src/App.tsx

@radikris What version of `chakra-react-select` / `react-select` / `chakra-ui` are you using?

**Comment by radikris** [comment]
@csandman for me, yes, now it's working fine with the types.  Great!


My other question would be, is it possible to have the feature that one dropdown item can be add several times?
I have the functionality in my app, that this select will list my orders, and I can add the same orders duplicated, but currently it's not supported, because it will be removed automatically from the list.
