### ISSUE TITLE
[BUG] Latest build doesn't include types

### ISSUE THREAD

**Issue by nvsd** [csandman/chakra-react-select#123]
### Description

It looks like types weren't included beyond 3.3.3.

### chakra-react-select Version

3.3.3

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Install `chakra-react-select`
2. View `node-modules/chakra-react-select/dist`
3. Observe `types` directory missing

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Thanks for the heads up!  This has been fixed in [v3.3.6](https://github.com/csandman/chakra-react-select/releases/tag/v3.3.6) (or [4.0.0-rc.2](https://github.com/csandman/chakra-react-select/releases/tag/v4.0.0-rc.2) for Chakra V2)

**Comment by nvsd** [comment]
Thanks for the quick turnaround and the library
