### ISSUE TITLE
[BUG] Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by larrysharette** [csandman/chakra-react-select#138]
### Description

`chakra-react-select` requires `@chakra-ui/react: 2.2.1`. It breaks on `@chakra-ui/react: 2.2.0`

### chakra-react-select Version

4.0.1

### Link to Reproduction

https://codesandbox.io/s/naughty-visvesvaraya-i8b13i?file=/pages/index.tsx

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Thanks for the heads up! Looks like this is happening with any version of Chakra UI under the most recent, 2.2.1.  I'm pretty sure I know what's causing it, I'll get a fix out sometime tomorrow.

**Comment by larrysharette** [comment]
Sounds great! Yeah I was wondering why I couldn't reproduce it in the code sandbox until I noticed it was on the latest version. So I bumped it back to 2.2.0 which is what I had locally and that's when it popped back up. I'm glad there is a workaround 🙂

**Comment by csandman** [comment]
Ok I ended up publishing a new version tonight, which I hope doesn't have any other issues.  This fix is mainly just reverting a change made in v4.0.0 so it shouldn't have any problems.
