### ISSUE TITLE
Long term support

### ISSUE THREAD

**Issue by blujedis** [csandman/chakra-react-select#16]
Please don't take offense :) It looks as though commits are regular etc. On a scale of 1-10 can you give me an idea as to commitment? Have a large project I'm considering using this lib in. Happy to contrib etc. Just wondering if author is currently using in production. Honestly no wrong answer here. Thanks in advance.

**Comment by csandman** [comment]
@blujedis Just a heads up, I implemented both of the major changes I had mentioned in the readme originally, adding a styling system in v2, and updating to react-select in v3. As far as LTS goes, I'd say this package now has pretty much everything it needs to survive, with most changes from now on being related to keeping the dependencies up to date.  I will of course still consider any feature requests anyone has that are in the scope of this package, but besides that there isn't anything that I still have planned to add besides the couple things left in the [Roadmap](https://github.com/csandman/chakra-react-select#roadmap).

If you want to give v3 of this package a try when you get a chance, I'd be glad to hear any feedback!  Especially if anything doesn't work right.

**Comment by csandman** [comment]
I'm going to close this for now as it has been answered
