### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Vazerthon** [csandman/chakra-react-select#163]
### Description

When I press the `tab` key while a select list is open I expect the next focusable element to be focused. Instead, items from the list are added to the current selection.

### chakra-react-select Version

4.1.3

### Link to Reproduction

https://codesandbox.io/s/chakra-react-select-vsvr0?file=/example.js

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Go to https://codesandbox.io/s/chakra-react-select-vsvr0?file=/example.js
2. Tab into select
3. Press down arrow to open list
4. Press tab a few times

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS/iPadOS
- [ ] Android

### Additional Information

![Peek 2022-07-26 16-33](https://user-images.githubusercontent.com/8657986/181048387-746bf8ce-ab66-4c2a-a3d0-3d91e39f38b4.gif)

**Comment by csandman** [comment]
Hey!  First off, this isn't a bug, its an intended behavior.  Second, not my intended behavior, its the default behavior of `react-select`.  Luckily there's an easy solution! `react-select` offers the `tabSelectsValue` prop which defaults to true.  If you pass in `tabSelectsValue={false}` the select will behave like you expect it to.

From the `react-select` docs:

> #### `tabSelectsValue`
> 
> Select the currently focused option when the user presses tab
> 
> `boolean`
>
> — https://react-select.com/props

Here's a complete example: https://codesandbox.io/s/chakra-react-select-tabselectsvalue-false-4b57dj?file=/example.js
