### ISSUE TITLE
Deselecting item when disabled

### ISSUE THREAD

**Issue by krystofex** [csandman/chakra-react-select#168]
### Description

If the selection is disabled (`isDisabled={true}`), the selected option can still be deselected by clicking on the cross.

![image](https://user-images.githubusercontent.com/48121710/187472444-debee0e0-5bdd-411b-bd4a-548ea696ed6e.png)

### chakra-react-select Version

2.0.0

### TypeScript?

- [ ] Yes I use TypeScript

### Steps to reproduce

1. Select some items
2. Disable select
3. Deselect them by clicking on the cross

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Thanks for the bug report! I have figured out what is wrong and will push a new version with a fix shortly.

**Comment by csandman** [comment]
This is now fixed in [`v4.1.5`](https://github.com/csandman/chakra-react-select/releases/tag/v4.1.5)!  Check out this demo to see it in action:

https://codesandbox.io/s/chakra-react-select-isdisabled-fix-vn24dg?file=/example.js
