### ISSUE TITLE
[BUG] menuIsOpen broken in 4.2.1

### ISSUE THREAD

**Issue by jezzzm** [csandman/chakra-react-select#176]
### Description

Looks like the changes in 4.2.1 for read-only behaviour broke the controlled functionality of react-select.

minimal repro: https://codesandbox.io/s/chakra-react-select-menuisopen-fjzmyt?file=/src/App.tsx

changing the dep to 4.2.0 in that CSB shows it working as intended

thanks!

### chakra-react-select Version

4.2.1

### Link to Reproduction

https://codesandbox.io/s/chakra-react-select-menuisopen-fjzmyt?file=/src/App.tsx

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. set `menuIsOpen` to true
2.  menu is not open

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Oops, I know what changed to break this, I'll take a look!

**Comment by jezzzm** [comment]
haha the number of times i've missed parens with nullish coalesce... not good!

thanks for the quickest fix ive ever seen, legend!
