### ISSUE TITLE
[BUG] Typescript types are not detected in nodeNext resolution environment

### ISSUE THREAD

**Issue by Inviz** [csandman/chakra-react-select#187]
### Description

When using `nodeNext` module resolution in typescript, react-chakra-select types are not detected. Because when `"exports"` is present, `"types"` at root level supposed to be ignored

Solution is to add 

> "types": "dist/types/index.d.ts" 

to package.json "exports" object after "default"

### chakra-react-select Version

4.2.2

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Create tsconfig with `"moduleResolution": "NodeNext",`
2. Include "chaka-react-select"
3. Try to typecheck

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
So just to get this clear, you just want me to change the `exports` key in the `package.json` to the following?

```json
"exports": {
  ".": {
    "require": "./dist/cjs/index.js",
    "default": "./dist/esm/index.js",
    "types": "dist/types/index.d.ts"
  }
},
```

**Comment by Inviz** [comment]
Yes sir. It's a safe change, as everything that need the JS will stop at `default`. But it will allow typescript to pick up the types. There's a little bit of uncertainty if it should be `index.d.ts` or `index.js`. Both works. However it seems  that `index.js` is more backward-compatible with older versions, but don't quote me on that. I'd add `index.d.ts.

```
"exports": {
  ".": {
    "require": "./dist/cjs/index.js",
    "default": "./dist/esm/index.js",
    "types": "./dist/types/index.d.ts"
  }
},
```

Little correction - `./dist`

**Comment by csandman** [comment]
ok cool, yes I can add that!  Thanks for bringing this to my attention

**Comment by csandman** [comment]
Should be published now in [`v4.2.3`](https://github.com/csandman/chakra-react-select/releases/tag/v4.2.3), let me know if you're still running into any issues!

**Comment by Inviz** [comment]
Seems to be smooth. many thanks for quick turnaround

**Comment by itsam** [comment]
Hello, this update broke my Next.js project (no Typescript). After upgrading to 4.2.3 I am getting 

```
Module not found: Default condition should be last one. 
> 1 | import { Select } from "chakra-react-select";
```
If I remove from node_modules (package.json) the following line, then everything works fine
`"types": "./dist/types/index.d.ts"`
I have tried to remove completely node_modules and yarn.lock and install again and the problem remains...

Thanks in advance

**Comment by Nithur-M** [comment]
@itsam I am facing the same issue.

**Comment by Inviz** [comment]
Oh my god, I'm really sorry it was my fault. I thought it's a good idea to do that. Which version of typescript is that? What's throwing the error? 

@csandman Sir I'm super sorry, looks like we need to rearrange it to make non-last. My bad.

**Comment by Inviz** [comment]
![](https://thumbs.dreamstime.com/b/flat-raster-dummy-person-icon-pictogram-isolated-white-background-166230254.jpg)

**Comment by itsam** [comment]
> Oh my god, I'm really sorry it was my fault. I thought it's a good idea to do that way. I did not get anything of that sort on my build. I thought it's a safe bet.
> 
> @itsam Which version of typescript is that? What's throwing the error? Is it yarn?
> 
> @csandman Sir I'm super sorry, looks like we need to rearrange it to make non-last. My bad.

Well, actually this is a general comment. I am not using TS in my project at all. Everything worked normally until I 've upgraded to 4.2.3. Quick search led me to this issue, and I tried to remove the line I mentioned above and everything worked again. So currently, version 4.2.3 is broken for non-TS next.js projects (cannot tell about TS)

Thank you for your great work and time :)

**Comment by luastoned** [comment]
CRA throws `Module not found: Error: Default condition should be last one`

**Comment by Inviz** [comment]
@Nithur-M Downgrade to previous version. Sorry again.

**Comment by csandman** [comment]
Thanks for the quick feedback @itsam @Nithur-M @luastoned I pushed a fix for this in [`v4.2.4`](https://github.com/csandman/chakra-react-select/releases/tag/v4.2.4).

> @Inviz
> 
> Oh my god, I'm really sorry it was my fault. I thought it's a good idea to do that way. I did not get anything of that sort on my build. I thought it's a safe bet.

Honestly, it's my fault for not doing much testing, didn't expect this to completely break the package for others.

> CRA throws `Module not found: Error: Default condition should be last one`
> 
> Here is the fix:
> 
> ```json
> "exports": {
>   ".": {
>     "import": "./dist/esm/index.js",
>     "require": "./dist/cjs/index.js",
>     "types": "./dist/types/index.d.ts",
>     "default": "./dist/esm/index.js"
>   }
> },
> ```
> 
> I explicitly added import and default should be last either way.

Thanks for the fix recommendation @luastoned, helped me get a new version out quick!

**Comment by csandman** [comment]
If anyone is still having issues, let me know ASAP!

**Comment by itsam** [comment]
I confirm replacing exports with 
```
"exports": {
  ".": {
    "import": "./dist/esm/index.js",
    "require": "./dist/cjs/index.js",
    "types": "./dist/types/index.d.ts",
    "default": "./dist/esm/index.js"
  }
},
```
fixes the bug :)

So, I would say it's OK to release the new npm (4.2.4)
Thank you everyone for the prompt reply.
Good job !!!

**Comment by itsam** [comment]
Oh, it's already online. Cross checked and works fine.

**Comment by csandman** [comment]
> Oh, it's already online. Cross checked and works fine.

Haha yep, I tested it myself in a test app first and it seemed to do the trick so I published quick.  Didn't want to leave a bug which brakes the whole package around for longer than I had to 😅

Thanks for confirming for me though!

**Comment by csandman** [comment]
Also I finally added the CodeSandbox CI GitHub app to more easily check if a PR works.  Hopefully that will help avoid silly mistakes like this in the future!

(you can see an example of it here: https://github.com/csandman/chakra-react-select/pull/193)
