### ISSUE TITLE
TypeError: Cannot read property 'Tag' of undefined [QUESTION] 

### ISSUE THREAD

**Issue by dribeirodev** [csandman/chakra-react-select#19]
I added your package to use multi select and my tests broke. Do you have any idea what it might be?

![image](https://user-images.githubusercontent.com/18536415/144134312-8df20c8e-5ff4-4abc-ac56-acd60eee8b9f.png)

![image](https://user-images.githubusercontent.com/18536415/144134431-3dd7e8cb-a856-43b7-985a-bd992fa3aa86.png)

**Comment by csandman** [comment]
I need a little more info to have any idea whats going on with this?

- What version of `chakra-react-select` are you on?
- What testing library are you using?
- How are you implementing `chakra-react-select`? (props passed into it, parent element, etc)
- How is your test interacting with `chakra-react-select` or sibling elements?

**Comment by keeeeith** [comment]
I'm also getting this error all of a sudden. The component was working fine and now it's not.

![Screen Shot 2021-12-07 at 10 49 56 PM](https://user-images.githubusercontent.com/58005205/145145206-7bce7c64-55a2-4cab-a13f-091fbd8f46c8.png)

**Comment by jonahallibone** [comment]
@keeeeith are you on the latest version of the component

**Comment by keeeeith** [comment]
Yeah I think it was related to a dependency duplicate/conflict of the Emotion package. While searching I came across others who'd had a similar dependency problem with react-select. When I got that straightened out the error went away.

**Comment by csandman** [comment]
@keeeeith What did you end up having to do to get the conflict sorted out?

**Comment by magnuslinden** [comment]
I'm seeing the same `TypeError: Cannot read properties of undefined (reading 'Tag')` error in my tests, running:
```
{
  "@chakra-ui/react": "^1.7.2",
  "react-select": "^4.3.1",
  "chakra-react-select": "^1.3.4",
  "@emotion/react": "^11.7.0",
}
```
and testing with jest + react testing library.

@keeeeith, you wouldn't happen to have a link to the dependency duplicate you with the emotion package that you managed to resolve in order to get rid of this error?

**Comment by magnuslinden** [comment]
Seems to originate from this line: https://github.com/csandman/chakra-react-select/blob/main/src/chakra-react-select.tsx#L448 which based on git blame looks like it had optional chaining on it 3 months ago.

**Comment by csandman** [comment]
@magnuslinden That would probably be the standard answer to this question. This component accesses the global Chakra theme for styles in case a user has overridden any of them. I tried to avoid hardcoding any chakra styles where I could to keep things looking consistent.

@dribeirodev Does wrapping your tests in a `<ChakraProvider />` fix your problem?

**Comment by csandman** [comment]
I'm going to close this for now as people seem to have found solutions to this problem, feel free to let me know if you're still having trouble with this and I'll re-open it.
