### ISSUE TITLE
[BUG] Unit tests fail when `Select` component is added to the DOM tree using vitest

### ISSUE THREAD

**Issue by han-sz** [csandman/chakra-react-select#199]
### Description

Using version `4.2.4` of the select component, `chakra-ui@2.3.4` + `vitest` I get the following error:
ReferenceError: Cannot access '__vite_ssr_import_5__' before initialization
```
ReferenceError: Cannot access '__vite_ssr_import_5__' before initialization
 ❯ node_modules/@chakra-ui/icon/dist/index.esm.js:11:6
      9| import { cx } from "@chakra-ui/shared-utils";
     10| const fallbackIcon = {
     11|   path: /* @__PURE__ */ React.createElement("g", {
       |      ^
     12|     stroke: "currentColor",
     13|     strokeWidth: "1.5"
 ❯ async /Users/user/Development/project/node_modules/@chakra-ui/layout/dist/index.esm.js:618:32
 ❯ async /Users/user/Development/project/node_modules/chakra-react-select/dist/esm/chakra-components/containers.js:22:31
 ❯ async /Users/user/Development/project/node_modules/chakra-react-select/dist/esm/chakra-components/index.js:1:256
 ❯ async /Users/user/Development/project/node_modules/chakra-react-select/dist/esm/use-chakra-select-props.js:9:31
 ❯ async /Users/user/Development/project/node_modules/chakra-react-select/dist/esm/select.js:24:31
 ❯ async /Users/user/Development/project/node_modules/chakra-react-select/dist/esm/index.js:3:31
```

When I remove the select component my tests are able to run perfectly.

### chakra-react-select Version

4.2.4

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Create a component that uses a provided select
2. Create a test that uses the component
3. Run test

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by han-sz** [comment]
A workaround is to load the component dynamically with `React.lazy` and `import`:

```
React.lazy(() => import('../components/MySelect`))
```

where `MySelect` is the component that loads the `Select` from this package.

**Comment by csandman** [comment]
Sorry, I thought I responded to this a while ago.  I am entirely unfamiliar with vitest, so there's not much I can do to recreate it or test.

I do see you commented here: https://github.com/chakra-ui/chakra-ui/issues/6783

So is it safe for me to assume that this is not an issue specific to `chakra-react-select` and is a problem with Chakra more generally?

**Comment by han-sz** [comment]
No worries, yes it seems like there are issues with Chakra and vitest compatibility. We can close the issue and then re-verify once the fix for Chakra is published
