### ISSUE TITLE
[BUG] React warning in Next.JS: React does not recognize the `getClassNames` prop on a DOM element

### ISSUE THREAD

**Issue by pianomansam** [csandman/chakra-react-select#223]
### Description

This is reproducible with either Next.js CodeSandbox:

- Next.js Vanilla JS: https://codesandbox.io/s/chakra-react-select-next-js-dtnsm?file=/pages/index.js
- Next.js TypeScript: https://codesandbox.io/s/chakra-react-select-next-js-typescript-kscuf?file=/pages/index.tsx

But it doesn't seem to occur in the CodeSandboxes that don't have Next.js.

This appears to be related to functionality [introduced](https://github.com/JedWatson/react-select/pull/5457) in [react-select@5.7.0](https://github.com/JedWatson/react-select/releases/tag/react-select%405.7.0).

This can be mitigated by pinning react-select to version [5.6.1](https://github.com/JedWatson/react-select/releases/tag/react-select%405.6.1) or earlier. However, because of the loose requirement versioning, this needs to be done with `resolutions`:

```
"resolutions": {
  "react-select": "5.6.1"
}
```

### chakra-react-select Version

4.4.1

### Link to Reproduction

- Next.js Vanilla JS: https://codesandbox.io/s/chakra-react-select-next-js-dtnsm?file=/pages/index.js
- Next.js TypeScript: https://codesandbox.io/s/chakra-react-select-next-js-typescript-kscuf?file=/pages/index.tsx

### TypeScript?

- [ ] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Ok, I fixed this by updating to the newest version of `react-select` and resolving the issue that arose due to the extra prop they added. I also pinned the dependency version of `react-select` to prevent changes there from causing issues with this package in the future.

For full details, see [`v4.2.2`](https://github.com/csandman/chakra-react-select/releases/tag/v4.4.2)

**Comment by hfz-r** [comment]
i think this bug also exists in v3. is there any workaround?

**Comment by csandman** [comment]
I can push a fix for v3 tomorrow!

**Comment by csandman** [comment]
@hfz-r Ok the fix is pushed in [v3.3.9](https://github.com/csandman/chakra-react-select/releases/tag/v3.3.9), let me know if it doesn't work for you because I didn't really test it

**Comment by hfz-r** [comment]
@csandman yes after update its work! thanks man.. you`re the best
