### ISSUE TITLE
[BUG]   selectedOptionColor doesn't work except for predfined colors like blue, red, purple

### ISSUE THREAD

**Issue by Moshappp** [csandman/chakra-react-select#238]
### Description

![Screen Shot 2023-02-10 at 2 41 59 AM](https://user-images.githubusercontent.com/117751089/217971532-c86947e1-baaa-42fe-a472-1cc3e3f6db2f.png)

I tried to set colors in hexdecimal and rgb formats as well as from the chakra theme, nothing happened. react-select working as expected.

### chakra-react-select Version

Latest

### TypeScript?

- [ ] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
This is a duplicate of #77 

You can set it to colors from the chakra theme, but only the name of the colors, not a specific number.

If you want to customize the colors more specifically than that you can use `chakraStyles`. See the linked issue for an example, or I can provide one here tomorrow.

**Comment by Moshappp** [comment]
Thank you for the fast response, I have figured it out from the duplicate issue.
