### ISSUE TITLE
[BUG] Users cannot make more than one selection in a multi selection dropdown at once when using a mobile phone

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [csandman/chakra-react-select#239]
### Description

When the user is using a mobile device selecting options from a multi select dropdown, the dropdown closes every time the user select an option. ie: the dropdown does not stay open after the first selection. Forcing the user to open the dropdown again and again for each item they want to select.

To reproduce just open the library examples of a multi select on a smartphone (I'm using an iPhone 13 - Safari )(https://codesandbox.io/s/chakra-react-select-typescript-4sce1?file=/app.tsx)

Do you guys know any work around? 

Thanks.

### chakra-react-select Version

3, 2,4

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

To reproduce just open the library examples of a multi select on a smartphone (I'm using an iPhone 13 - Safari )(https://codesandbox.io/s/chakra-react-select-typescript-4sce1?file=/app.tsx)

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
This is a behavior of `react-select` itself, and it's easy enough to get around using `blurInputOnSelect={false}` along with `closeMenuOnSelect={false}`.

```tsx
<Select
  isMulti
  closeMenuOnSelect={false}
  blurInputOnSelect={false}
/>
```

CodeSandbox: https://codesandbox.io/s/1jk88f?file=/app.tsx

**Comment by csandman** [comment]
I'm going to close this as a solution is available, let me know if you're still having problems
