### ISSUE TITLE
[BUG] Invalid font color when trying to change Input component

### ISSUE THREAD

**Issue by hadson172** [csandman/chakra-react-select#245]
### Description

When using chakra-react-select with dark mode and trying to setup custon Input component (as a number) font color is dark.
`<Select
        components={{
          Input: (props) => {
            return <components.Input {...props} type={"number"} />}}}
/>`

![obraz](https://user-images.githubusercontent.com/8881977/220988406-c9f27c27-a329-4a44-ab3b-fd47712e3e22.png)

### chakra-react-select Version

4.5.0

### TypeScript?

- [X] Yes I use TypeScript

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
If you're importing components like so:

```ts
import { components } from "chakra-react-select"
```

Then you are importing the original components from the `react-select` package. To import the CRS version, use the following:

```ts
import { chakraComponents } from "chakra-react-select"
```

**Comment by hadson172** [comment]
Tried this as well. Seems that even then <Text /> with type={"number"} does not work properly. (allows for non digit characters). Is there any solution for this in chakra-react-select?

**Comment by hadson172** [comment]
Try to type any letter. You will notice that something is visible but overflown. (firefox)

**Comment by csandman** [comment]
It appears to be working fine for me. Are you on Windows?  Also like I was asking for, what's the use case here? There might be a better solution than using a `number` input.

**Comment by hadson172** [comment]
My goal was to build build component allowing users to pick a Year. Important thing was to display on mobiles number keyboard instead of standard.

**Comment by csandman** [comment]
> My goal was to build build component allowing users to pick a Year. Important thing was to display on mobiles number keyboard instead of standard.

Ah, if mobile is your primary goal, I highly recommend using the [`inputMode="numeric"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) prop on your custom input component. This is the best way to hint to mobile devices which keyboard type to display without needing to change the input's `type`.

Here's an example: https://codesandbox.io/s/qw2pn7?file=/app.tsx

Or if you want to try it on mobile, here's a full page example: https://qw2pn7.csb.app/

**Comment by csandman** [comment]
Some solutions have been provided so I'm going to close this issue, let me know if there's any other issues you're having
