### ISSUE TITLE
[BUG] Vitest test crashes when using chakra-react-select.

### ISSUE THREAD

**Issue by dallalgaham** [csandman/chakra-react-select#256]
### Description

I am using chakra-react-select in one of my component as the following: 
```

{/* Industries */}
	<FormControl id="industries" isInvalid={formik.touched.industries && Boolean(formik.errors.industries)}>
		<CreatableSelect 
		        isMulti
			options={industries}
			placeholder='Industries'
			closeMenuOnSelect={false}
			onChange={async (value) => {
			         formik.setFieldValue('industries', value.map(item => item.value));
			}}
		/>
	        <FormErrorMessage>{formik.errors.industries}</FormErrorMessage>
	</FormControl>
```

I am really happy with the functioning of my component the only issue is when I try to run my test: 

```
import {render} from '@testing-library/react';
import OrganizationSignupForm from '.';
import {vi} from 'vitest';

describe('OrganizationSignupForm', () => {
	it('renders without crashing', () => {
		const onSubmit = vi.fn();
		render(<OrganizationSignupForm onSubmit={onSubmit} />);
	});
});

```

It crashes and give me the following error message: 
<img width="749" alt="Screenshot 2023-04-10 at 13 42 05" src="https://user-images.githubusercontent.com/100210438/230896393-24e23b4f-a981-42ae-83ea-3e1c3fcb8376.png">

### chakra-react-select Version

4.6.0

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Have you taken a look at this related issue? https://github.com/csandman/chakra-react-select/issues/199

**Comment by barrymichaeldoyle** [comment]
I experience the same exact error in my jest tests (not using vitest). Been struggling with this all day.

**Comment by csandman** [comment]
@barrymichaeldoyle Have you ensured that it's being rendered inside a chakra provider? It will error out otherwise.

**Comment by barrymichaeldoyle** [comment]
@csandman that did the trick for me :) Maybe it will solve this vitest issue as well 👍

**Comment by csandman** [comment]
Glad to hear it! I mentioned a similar solution here if you want to see a more in depth answer: #198
