### ISSUE TITLE
[BUG] Warning: Prop `id` did not match. Server: 

### ISSUE THREAD

**Issue by Kolby-Udacity** [csandman/chakra-react-select#260]
### Description

Using the latest verion of Chakra: 2.5.3
And the latest version of chakra-react-select: 4.6.0

The warning `Warning: Prop `id` did not match. Server: "react-select-chakra-react-select-1-input" Client: "chakra-react-select-demo"` Appears in the console.

### chakra-react-select Version

4.6.0

### Link to Reproduction

https://codesandbox.io/s/laughing-turing-9089o6

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Go to https://codesandbox.io/s/laughing-turing-9089o6
2. Look in console

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Sorry for the delay, but I believe my latest change to correctly support ESM imports should actually fix this issue, and prevent the need for the workaround! You can see the details in [`v4.9.0`](https://github.com/csandman/chakra-react-select/releases/tag/v4.9.0)
