### ISSUE TITLE
[BUG] useBasicStyles type error on Vite

### ISSUE THREAD

**Issue by haw0k** [csandman/chakra-react-select#281]
### Description

When using vite + react-ts I get error TS2322 if I set useBasicStyles in props

### chakra-react-select Version

4.7.1

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. yarn create vite vite-test --template react-ts
2. cd vite-test
3. yarn add @chakra-ui/react @emotion/react @emotion/styled framer-motion chakra-react-select
4. replace src/App.tsx by 
```
import { ChakraProvider } from '@chakra-ui/react';
import { Select } from 'chakra-react-select';

function App() {
  return (
    <ChakraProvider>
      <Select useBasicStyles />
    </ChakraProvider>
  )
}
export default App
```
5. Add to package.json "scripts":
```
"lint-tsc": "tsc --noEmit && eslint src/**/*.ts{,x}",
```
6. Run `yarn lint-tsc`
7. Got error:
```
$ yarn lint-tsc
yarn run v1.22.19
$ tsc --noEmit && eslint src/**/*.ts{,x}
src/App.tsx:7:15 - error TS2322: Type '{ useBasicStyles: true; }' is not assignable to type 'IntrinsicAttributes & Omit<PublicBaseSelectProps<unknown, false, GroupBase<unknown>>, StateManagedPropKeys> & Partial<...> & StateManagerAdditionalProps<...> & RefAttributes<...>'.
  Property 'useBasicStyles' does not exist on type 'IntrinsicAttributes & Omit<PublicBaseSelectProps<unknown, false, GroupBase<unknown>>, StateManagedPropKeys> & Partial<...> & StateManagerAdditionalProps<...> & RefAttributes<...>'.

7       <Select useBasicStyles />
                ~~~~~~~~~~~~~~


Found 1 error in src/App.tsx:7
```

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS/iPadOS
- [ ] Android

### Additional Information

No errors for create-react-app

**Comment by csandman** [comment]
Thanks for the heads up, somehow some local changes got included in my publish of `v4.7.1`. Everything should be fixed in [`v4.7.2`](https://github.com/csandman/chakra-react-select/releases/tag/v4.7.2)!
