### ISSUE TITLE
[BUG] peerDependencies to Chakra v2 still show up

### ISSUE THREAD

**Issue by fabiradi** [csandman/chakra-react-select#301]
### Description

chakra-react-select claims to require **Chakra UI v3**, but still has `peerDepemdensies` referring to v2.

### yarn install
```
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/form-control@^2.0.0".
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/icon@^3.0.0".
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/layout@^2.0.0".
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/media-query@^3.0.0".
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/menu@^2.0.0".
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/spinner@^2.0.0".
(project) > chakra-react-select@4.7.6" has unmet peer dependency "@chakra-ui/system@^2.0.0".
```

Is that correct? Or does that need to be updated? It keeps popping up and I would like to get this solved.

### chakra-react-select Version

4.7.6

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Add `chakra-react-select@4.7.6` as a dependency
2. Run `yarn install`

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
I'm confused what you mean by this, if you look at the description in the docs, it does specifically say Charka v2:

> This version of chakra-react-select is updated for [Chakra UI v2](https://chakra-ui.com/getting-started/migration) which works exclusively with React v18. chakra-react-select v3 will be maintained until the majority of users have migrated. If you're still using Chakra UI v1 check [the docs for chakra-react-select v3 here](https://github.com/csandman/chakra-react-select/tree/v3).

Maybe you're getting confused by my distinguishing v3 of this package? Chakra UI (specifically the combined React package) doesn't even have a v3 yet.

**Comment by csandman** [comment]
They show up because they're dependencies of `@chakra-ui/react` and not direct dependencies of your project. It is something I have noticed specifically with yarn though, as I haven't seen these warnings with NPM >= v7 (or maybe it's v6).

**Comment by fabiradi** [comment]
That's fine for me. It's not this library, but yarn. You may close this bug.

**Comment by csandman** [comment]
Cool, glad you got it figured out!
