### ISSUE TITLE
[BUG] Cannot start the application when using chakra-react-select with Vite

### ISSUE THREAD

**Issue by dk-khoado** [csandman/chakra-react-select#303]
### Description

@chakra-ui: 2.8.2
Vite: 4.4.9

![image](https://github.com/csandman/chakra-react-select/assets/43430177/d5c7c173-0d17-4582-b79f-cd54d9ada7b5)

### chakra-react-select Version

4.7.6

### TypeScript?

- [X] Yes I use TypeScript

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by jonahallibone** [comment]
Can you provide a reproduction?

**Comment by Khoado148** [comment]
Hi @jonahallibone thank you for reply
i using yarn 3. It seems it didn't install these packages for me. It worked when I installed the above packages myself. Is there any other way to avoid having to install it manually?

"@chakra-ui/form-control": "^2.0.0"
"@chakra-ui/icon": "^3.0.0"
"@chakra-ui/layout": "^2.0.0"
"@chakra-ui/media-query": "^3.0.0"
"@chakra-ui/menu": "^2.0.0"
"@chakra-ui/spinner": "^2.0.0"

**Comment by dk-khoado** [comment]
Hi @jonahallibone thank you for reply
i using yarn 3. It seems it didn't install these packages for me. It worked when I installed the above packages myself. Is there any other way to avoid having to install it manually?

"@chakra-ui/form-control": "^2.0.0"
"@chakra-ui/icon": "^3.0.0"
"@chakra-ui/layout": "^2.0.0"
"@chakra-ui/media-query": "^3.0.0"
"@chakra-ui/menu": "^2.0.0"
"@chakra-ui/spinner": "^2.0.0"

**Comment by csandman** [comment]
This should be fixed in the most recent version `v4.10.0`
