### ISSUE TITLE
[BUG] Custom components automatically switch to Chakra style instead of keeping default

### ISSUE THREAD

**Issue by mhamid3d** [csandman/chakra-react-select#304]
### Description

I have a custom `Option` component, even if I just return a `components.Option` component, with no changes, the style is completely different. **It's better visible in dark mode,** I have provided a sandbox with 2 Select components, one with a custom Option, and another is just default Select. Check the colors of the Options when you hover and select, despite not changing anything related to the style, it seems to be picking on Chakra style colors.

I expected the style to remain the same unless I explicitly change it.

### chakra-react-select Version

4.7.6

### Link to Reproduction

https://codesandbox.io/s/chakra-react-select-chakrastyles-forked-qvmqkp?file=/app.tsx

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
You need to import the components from `chakraComponents`, not `components`. `components` is the original components from react select.
