### ISSUE TITLE
[BUG]: No `ValueType` export for the `onChange` handler

### ISSUE THREAD

**Issue by RobertGemmaJr** [csandman/chakra-react-select#305]
### Description

Getting the following error when I attempt to type the value inside the component:

> Type '{ size: SizeProp; useBasicStyles: true; options: Option[]; defaultValue: Option; onChange: (option: SingleValue<Option>) => void; }' is not assignable to type 'Partial<PublicBaseSelectProps<unknown, boolean, GroupBase<unknown>>>'.
  Types of property 'onChange' are incompatible.
    Type '(option: SingleValue<Option>) => void' is not assignable to type '(newValue: unknown, actionMeta: ActionMeta<unknown>) => void'.
      Types of parameters 'option' and 'newValue' are incompatible.
        Type 'unknown' is not assignable to type 'SingleValue<Option>'.ts(2322)

The component looks like so:

```tsx
export type Option = OptionBase & {
  value: string;
  label: string;
};

const OPTIONS: Option[] = [
  { value: "10", label: "Show 10" },
  { value: "20", label: "Show 20" },
  { value: "30", label: "Show 30" },
  { value: "40", label: "Show 40" },
  { value: "50", label: "Show 50" },
  { value: "100", label: "Show 100" },
];

return (
...
      {/* TODO: Ref is not pushing ref to the correct position */}
      <SelectInput
        size={size}
        useBasicStyles={true}
        options={OPTIONS}
        defaultValue={
          // Initialize selected to the current page size
          OPTIONS.find((option) => Number(option.value) === pagination.pageSize) ?? OPTIONS[0]
        }
        onChange={(option: SingleValue<Option>) => {
          setPageSize(Number(option?.value));
        }}
      />
...
)
```

The closest solution I've found is to re-export the `ValueType` from `react-select` in this component. I've already looked through [this discussion](https://github.com/JedWatson/react-select/issues/2902) (as well as others) on the `react-select` library

### chakra-react-select Version

3.3.1

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

### Additional Information

I've already looked through [this discussion](https://github.com/JedWatson/react-select/issues/2902) (as well as others) on the `react-select`

**Comment by RobertGemmaJr** [comment]
This is the only way I was able to satisfy typescript:

```ts
      <SelectInput
        size={size}
        useBasicStyles={true}
        options={OPTIONS}
        defaultValue={
          // Initialize selected to the current page size
          OPTIONS.find((option) => Number(option.value) === pagination.pageSize) ?? OPTIONS[0]
        }
        onChange={(newValue: SingleValue<unknown>) => {
          const option = newValue as Option;
          setPageSize(Number(option.value));
        }}
      />
```

**Comment by csandman** [comment]
So the `ValueType` shouldn't really be necessary in most use cases, and it's hard to tell exactly what's going on with your type error without having an example to show how you got there. I tried to take what you have here and put it in a CodeSandbox and everything worked fine, so if you could provide an example that shows the error I could try and give you more help: https://codesandbox.io/s/valuetype-example-gt3qtv?file=/app.tsx

The only thing I can say is that when you're using a single select, you can type the argument of your `onChange` function as `Option | null`, and it should just work.

**Comment by RobertGemmaJr** [comment]
@csandman I was able to fork and update the sandbox such that the error appears. The select is inside of a tanstack table which I suppose is the cause? https://codesandbox.io/s/valuetype-example-forked-jmnvy8?file=/components/table/partials/Pagination.tsx

The typescript error is in `components/table/partials/Pagination.tsx`. The component is used inside the Table component (`components/table/Table.tsx`) and I've updated `App.tsx` to be an example use of the table component. Let me know if I can clean up or explain the sandbox more!

**Comment by csandman** [comment]
Ah, yeah there's no way I could have given you an answer without this reproduction. The issue is that you made a custom wrapper for the select without forwarding the generics, so the type inference can't happen. It's just using the default type for `Option` which is `unknown`. You should also be using the exported type for the props instead of using the react type util:

```tsx
import { type GroupBase, Select, type Props} from "chakra-react-select";

export type SelectInputProps = Props;

/** A chakra-react-select {@link Select} component */
export function SelectInput<
Option = unknown,
IsMulti extends boolean = false,
Group extends GroupBase<Option> = GroupBase<Option>,
>({
  focusBorderColor = "primary.500",
  ...delegated
}: Props<Option, IsMulti, Group>) {
  return <Select focusBorderColor={focusBorderColor} {...delegated} />;
}
```

And here's a functional example: https://codesandbox.io/s/75ztwy?file=/components/table/partials/Pagination.tsx

**Comment by RobertGemmaJr** [comment]
Okay sweet, thank you for this! Do you know if it's possible to use the Chakra `forwardRef` component as well? The auto-positioning isn't working currently. Not sure if it's possible to pass the generics to the function.

![image](https://github.com/csandman/chakra-react-select/assets/38439940/032f4c7e-41e1-407e-9970-1a97ba61422b)

**Comment by csandman** [comment]
You can make use of `forwardRef`, yes, but it's a bit more complicated to make it fully generic with it. You can find more info about it in this issues: https://github.com/csandman/chakra-react-select/issues/81

But I'm not sure exactly what you're trying to do. If you can give me more info on what you mean by "auto-positioning isn't working currently" I can probably give you better advice.

**Comment by RobertGemmaJr** [comment]
Got the ref working as  well! This is a possible alternative solution to #95.

```ts
import { forwardRef } from "@chakra-ui/react";
import {
  Select,
  type GroupBase,
  type SelectComponent,
  type SelectInstance,
  type Props as SelectProps,
} from "chakra-react-select";
import type { ForwardedRef } from "react";

/** Re-export of the props of the chakra-react-select Select component */
export type SelectInputProps<
  Option = unknown,
  IsMulti extends boolean = false,
  Group extends GroupBase<Option> = GroupBase<Option>,
> = SelectProps<Option, IsMulti, Group>;

/** A chakra-react-select Select component */
export const SelectInput = forwardRef<SelectInputProps, typeof Select>(
  (
    { focusBorderColor = "primary.500", menuPlacement = "auto", ...delegated }: SelectInputProps,
    ref: ForwardedRef<SelectInstance>
  ) => {
    return (
      <Select
        ref={ref}
        focusBorderColor={focusBorderColor}
        menuPlacement={menuPlacement}
        {...delegated}
      />
    );
  }
) as SelectComponent;
```

It uses the `fowardedRef` from Chakra instead of React. This would allow for the `as` prop to be used from Chakra, although the `SelectComponent` type would have to be updated as well. I don't expect to have to use the `as` prop for this component (just written this way for consistency between components) so it may not be worth your while? Just wanted to pass along!

**Comment by csandman** [comment]
> Okay I was able to figure it out one issue but it was a totally unrelated thing. The dropdown was in the wrong place (see the screenshot above) but all I had to do was set the prop `menuPlacement = "auto"`!

Technically not the wrong place haha, that's just the default behavior of `react-select`.

>  That feels like a good default for the prop but not sure how that fits into your design philosophy for how you're building off `react-select` props.

Honestly, I have thought about this, as it would line up better with how Chakra's Menu works by default. However, I don't change any of `react-select`'s other default props in any other places (only extend them by adding new ones), so I figured I'd leave it alone to avoid confusion. Plus it's very easy to change if you so choose. But who knows, maybe I'll revisit this in the future.

**Comment by RobertGemmaJr** [comment]
Yeah that's what I figured - not touching the defaults feels like a smart thing to do. Little bit of confusion on my part but when I went to the `react-select` documentation I figured it out right away. Cheers!

**Comment by csandman** [comment]
Glad to hear you figured it out! Like I mention in the docs, a lot of the issues people end up having are answered by the original `react-select` docs. And a good strategy for finding answers to issues with this package is just to google the issue with `react-select` instead of `chakra-react-select`. It's such a popular package that people have figured out how to do all kinds of things with it, and most of the answers apply to this package too.
