### ISSUE TITLE
[BUG] Tag close button is not working in Multi Select mode

### ISSUE THREAD

**Issue by wlwong703** [csandman/chakra-react-select#31]
**Describe the bug**
When clicking the close button of the selected tag, it does nothing.

**Link to Reproduction**
https://codesandbox.io/s/chakra-react-select-next-js-dtnsm?file=/pages/index.js

**To Reproduce**

1. Select an Option
2. Click the Tag Close Button

**Expected behavior**
It should remove the selected option.

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome
- Version: 97.0.4692.71

**Comment by csandman** [comment]
Wow that's a pretty rough bug, thanks for letting me know!  I figured something slipped through the cracks, I think that came from one of the last changes I made in `3.0.0` which is why I must have missed it.

It has been fixed in `v3.0.1`, let me know if you're still having any issues!
