### ISSUE TITLE
[BUG] LoadOptions doesn't render options when isMulti = True and there is already one selected option in component

### ISSUE THREAD

**Issue by Rezaabdi78** [csandman/chakra-react-select#311]
### Description

I have enabled `isMulti` for my `AsyncSelectComponent`. Also, I have defined an async function that fetches data from a REST API and does some processing on data. 
After the first search and data fetching, all the options that should be rendered are presented and the component works fine. 
The moment you choose the first option and try to open the select component again, the fetching data process goes underway and fetches data. Still, there are no options rendered in the dropdown of the select component. 

### chakra-react-select Version

4.7.6

### Link to Reproduction

[Link to Reproduction](https://codesandbox.io/p/sandbox/chakra-react-select-custom-loadingindicator-forked-8c4cjh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clspyjyw60007356lr7wczn08%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clspyjyw60003356lrlrefxme%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clspyjyw60004356lr2gq4o47%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clspyjyw60006356l6bmqpjzb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clspyjyw60003356lrlrefxme%2522%253A%257B%2522id%2522%253A%2522clspyjyw60003356lrlrefxme%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clspykizi0002356l8e5y7att%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fexample.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522clspykizi0002356l8e5y7att%2522%257D%252C%2522clspyjyw60006356l6bmqpjzb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clspyjyw60005356l6gl09ocm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clspyjyw60006356l6bmqpjzb%2522%252C%2522activeTabId%2522%253A%2522clspyjyw60005356l6gl09ocm%2522%257D%252C%2522clspyjyw60004356lr2gq4o47%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clspyjyw60004356lr2gq4o47%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Go to the CodeSandbox Link provided
2. Click on Dropdown or start typing (It just shows 5 data which is fine and working properly)
3. try to choose one of the options and it's working. 
4. try to choose ANOTHER option and the dropdown does not show any options, although the fetching process is completed.
5. observe the console to see a log of data that should render in component.

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
There are a couple issues with the example you provided. First, the function you use to map the search results to options for the select isn't returning a valid option object to match your select options.

You are returning:

```ts
{ label: r.name, id: i }
```

Where as by default, `react-select` uses the structure `{ label, value }`

You'd have to either change the structure of the returned options, or pass the `getOptionValue` prop to the Select component:

```tsx
<Select getOptionValue={(option) => option.id} />
```

Another issue here is that you're using the index of the options for the `id` field. `react-select` uses the value field to determine which options are already selected (and hidden), so if that value is dynamic, random options will be hidden from the returned options object.

By changing the example you provided to return the `name` value for both the `label` and the `value` fields, everything appears to work fine:

```tsx
const promiseOptions = async (inputValue: string) => {
  const data = await fetch(
    `https://pokeapi.co/api/v2/pokemon?limit=5&offset=0`
  );
  if (await data.ok) {
    const x = await data.json();
    console.log(x.results.map((r, i) => ({ label: r.name, value: r.name })));
    return x.results.map((r, i) => ({ label: r.name, value: r.name }));
  }
};
```

Also, I'm not sure what's going on with your `loadOptions` prop, but you could just pass in `promiseOptions` and the functionality would be the same.

```tsx
loadOptions={promiseOptions}
```
