### ISSUE TITLE
[BUG] Incompatible with Chakra UI Pro theme

### ISSUE THREAD

**Issue by chriskuech** [csandman/chakra-react-select#316]
### Description

When I installed Chakra UI Pro theme and import `chakra-react-select`, then the app crashes with the following stack traces:
<img width="806" alt="image" src="https://github.com/csandman/chakra-react-select/assets/3680671/02bea2b9-8fff-48e7-b196-875540a5a6a8">

### chakra-react-select Version

4.7.6

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Install and configure Chakra UI Pro theme
2. Instantiate a `Select` from chakra-react-select

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment]
Can you give me a code example of how the app is set up? I've never used the Chakra pro theme, so it's hard for me to diagnose this without an example.

**Comment by chriskuech** [comment]
Ya its just [this guide](https://pro.chakra-ui.com/guides/get-started). It's basically just copying in a chakra theme file.

**Comment by csandman** [comment]
Ok, actually looking at the part of the error `Cannot read properties of undefined (reading '500')`, this makes me think this package is not able to find one of the basic color palettes for `red` or `blue` that the normal theme has. Are the base color scheme colors not available in the pro theme color palette?

If not, you'd have to pass the `selectedOptionColorScheme` prop with some color palette the theme actually has. I believe this should fix the issue but let me know if not.

**Comment by csandman** [comment]
Since no more information has been provided and this has been stale for a while, I'm going to close it. If there's anything else you need, I can re-open the issue.
