### ISSUE TITLE
[BUG] When selecting default values in a form, these values will still be selectable inside the dropdown (zod)

### ISSUE THREAD

**Issue by breathTake** [csandman/chakra-react-select#327]
### Description

When i set defaultValues, I expect these values to be removed from the dropdown, but instead i can select them once more.

When I edit an Object inside a form, I pass default values. It doesnt work with zods typical `register{...prop}`, instead i tried it with the default values prop.

The default Values will still be selectable inside the dropdown -> I can have the same Tag selected twice

```        
<ControlledSelect<FormData, SkillOptions, true>
          isMulti
          name="skills"
          label="Fähigkeiten"
          placeholder="Suchen..."
          openMenuOnFocus
          closeMenuOnSelect={false}
          useBasicStyles
          control={control}
          tagVariant='solid'
          colorScheme='blue'
          selectedOptionStyle="check"
          options={skillsForSelect} 
          defaultValue={transfSkills}
          hideSelectedOptions={true}
/>
```

![image](https://github.com/user-attachments/assets/03577b39-7746-4a0e-8b78-2c15a2a2e3b6)

### chakra-react-select Version

^4.8.0

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Define mockData as Options inside Select
2. Take some Objects of that data and put them as default values into the Select Comp.
3. See that the Default Values and in addition to that the same Objects inside the mockData will be displayed in the dropdown

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by breathTake** [comment]
Hello again, i really need a solution for that

**Comment by csandman** [comment]
Also, when you say, "It doesnt work with zods typical `register{...prop}`", are you actually talking about `react-hook-form`? If so, you also don't want to be using `defaultValue` on the select component. Instead, you'd want to be passing it into the `defaultValues` config in the `useForm` hook:

```tsx
  const {
    control,
    handleSubmit,
    register,
    reset,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    defaultValues: {
      mySelectValues: [
        { label: "V...", value: "v..." }
      ]
    },
  });

**Comment by breathTake** [comment]
During the construction of the sandbox i realised the `skillsForSelect` are made` toLowerCase()`and the `transfValues` arent. Thats why they werent seen as the same values

Now its working, thank you for making me realise <3! 
And yes i didnt realise the register prop wasnt needed and the default values would be automatically inserted i defined in defaultValues!

For anyone in the future thats how the code looks now:
```
 defaultValues: {
      skills: defaultSkills,
      ...
}
---       
<ControlledSelect<FormData, SkillOptions, true>
          isMulti
          name="skills"
          label="Fähigkeiten"
          placeholder="Suchen..."
          openMenuOnFocus
          closeMenuOnSelect={false}
          useBasicStyles
          control={control}
          tagVariant='solid'
          colorScheme='blue'
          selectedOptionStyle="check"
          options={skillsForSelect} 
          hideSelectedOptions={true}
        />
```
