### ISSUE TITLE
[BUG] Error: Uncaught [Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `ForwardRef`.]

### ISSUE THREAD

**Issue by hatajoe** [csandman/chakra-react-select#329]
### Description

When I run `yarn jest`, I expected pass the test to happen but the above error happened instead.
This error happens in v4.9.0 or greater, but it doesn't happen in v4.8.0. 

Do you have any ideas to solve this?

### chakra-react-select Version

4.9.0

### Link to Reproduction

https://codesandbox.io/p/devbox/yhhghw

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

1. Go to https://codesandbox.io/p/devbox/yhhghw
2. Click on `New Terminal`
3. type `yarn jest` and hit return key

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by mareksuscak** [comment]
Facing the same issue here and it's also only happening in a test environment (coincidentally also using Jest). Our Jest currently doesn't support Pure ESM modules and it seems that version 4.9.0 switched this module to ESM only or at least made related changes to the package.json - see https://github.com/csandman/chakra-react-select/compare/v4.8.0...v4.9.1

**Comment by csandman** [comment]
I see, yeah `v4.9.0`/`v4.9.1` updated the package to make ESM work properly, where as before that it was kind of "fake" ESM, but this package still has a CommonJS version. You can see more info about it in [my PR description for 4.9.0](https://github.com/csandman/chakra-react-select/pull/298). If this is causing the issue, it should be possible to force jest to get the CJS version of this package, but I'm not 100% sure of the proper way. I don't have a ton of experience getting Jest to look for the proper versions of files. It should

I'll try and see if I can find the right config change necessary to get this to work properly and get back to you.

**Comment by csandman** [comment]
Ok, so I ended up switching the `"type"` of the project back to the default of `"commonjs"`, and this fixes the issue for me. If you install [`v4.9.2`](https://github.com/csandman/chakra-react-select/releases/tag/v4.9.2), let me know if the issue is fixed for you all!

**Comment by hatajoe** [comment]
@csandman I was able to upgrade successfully. Thank you for the quick fix!
