### ISSUE TITLE
Dark mode text color should change

### ISSUE THREAD

**Issue by codebuzzco** [csandman/chakra-react-select#4]
![image](https://user-images.githubusercontent.com/90099080/134766223-27e93af1-cfec-418f-91c6-9a4f19ba3af6.png)

**Comment by csandman** [comment]
Just fixed, let me know if you're still having any issues!

**Comment by codebuzzco** [comment]
Looks great! 🙌 Thank you.

**Comment by csandman** [comment]
Glad to hear it!  I'll admit, I haven't spent nearly as much time testing this without `isMulti` because that felt like the main appeal.  However, I definitely want it to handle all use cases!
