### ISSUE TITLE
[FEATURE] Allow any React.ReactNode to be a label

### ISSUE THREAD

**Issue by lcswillems** [csandman/chakra-react-select#41]
Currently labels can only be strings. It is very restrictive. I would like them to be a React Node as React Select allows it.

![image](https://user-images.githubusercontent.com/5437552/151164646-6c52bf45-4f7c-4c8a-96da-69d0875746ef.png)

**Comment by csandman** [comment]
I'll take a look at this! I'm not sure why this package would handle react nodes as labels differently than the original package.  Do you have an example of what happens, like a CodeSandbox? I have [templates in my Readme](https://github.com/csandman/chakra-react-select#codesandbox-templates) if you need. Also are you using TypeScript or vanilla JS?

**Comment by lcswillems** [comment]
After digging in, you are right that the limitation comes from the react-select. Maybe this issue should be closed and I should open a new one in react-select

**Comment by csandman** [comment]
Ah ok, that makes more sense.  However, you aren't fully out of options.  One way you could get the behavior you're looking for is by extending the `Option` component exported from this package to render custom elements you keep on your options object.

Here's a quick example I made demonstrating how to do it: https://codesandbox.io/s/chakra-react-select-custom-option-d99s7?file=/example.js

```js
const Example = () => (
  <Select
    isMulti
    name="colors"
    options={flavourOptions}
    placeholder="Select some colors..."
    closeMenuOnSelect={false}
    components={{
      Option: ({ children, ...props }) => (
        <chakraComponents.Option {...props}>
          {props.data.icon} {children}
        </chakraComponents.Option>
      )
    }}
  />
);
```

If this suits your needs then feel free to close it for now.  I don't plan on adding any features that fundamentally change the inner workings of `react-select`, so you're better off asking there if its something you'd like natively added.

However, if you have any more questions let me know!

**Comment by lcswillems** [comment]
Thanks a lot for your help!!
