### ISSUE TITLE
Upgrade to React-Select v5.0

### ISSUE THREAD

**Issue by pianomansam** [csandman/chakra-react-select#5]
React-Select has been upgraded to v5.0 and completely rewritten in TypeScript.

https://github.com/JedWatson/react-select/releases/tag/react-select%405.0.0

**Comment by csandman** [comment]
Wow, what timing haha.  I'll get a new version pushed up ASAP!

**Comment by csandman** [comment]
Just installed to see what happens, and a lot of my types are broken haha.  Unfortunately I'm very new to typescript so it will probably take me a while to figure out how to fix everything, but if anyone wants to give it a shot in the mean time, feel free!

@bbovenzi @ejoc

**Comment by zanami** [comment]
This might be useful https://github.com/JedWatson/react-select/issues/4804#issuecomment-927223471

**Comment by sshyam-gupta** [comment]
@csandman can I try and help here?

**Comment by csandman** [comment]
@sshyam-gupta be my guest!  To give it a shot, you can just upgrade react-select to latest, and remove `@types/react-select` and see about replacing it.  I think one of the main things I don't have set up properly is the generics.  If you have any questions let me know!

**Comment by sshyam-gupta** [comment]
@csandman How do I validate this? any contribution doc?

**Comment by csandman** [comment]
I am working on a contribution doc, but I'm still figuring it out.

By "validate" do you mean test it to make sure it works? Or that it passes all lint rules? Because I have pre-commit hooks set up to ensure it passes all lint rules before anything gets pushed.

**Comment by sshyam-gupta** [comment]
yes @csandman , I made changes and want to test if it works. Is there any script available or I need to npm link to package?

**Comment by csandman** [comment]
There in nothing in the main branch set up for testing right now, there is a storybook branch in progress but it's not ready to merge into main yet, however it is functional so you could try your changes against that if you'd like. Otherwise an npm link is probably your best bet.

**Comment by csandman** [comment]
I know it took a while but i finally updated to `react-select@5`!  It involved some major structural changes to the code, but the result is that I think the types are finally implemented correctly.  Please give `3.0.0` a try when you can and leave a new issue if something broke!

Also thanks to @zanami for the link about module augmentation, that ended up being one of the most important strategies I had to use to make this wrapper work correctly.
