### ISSUE TITLE
[FEATURE] react-hook-form support

### ISSUE THREAD

**Issue by manuelpoelzl** [csandman/chakra-react-select#63]
It would be great if this component would support react-hook-form, so that you can set an error validation or policy like a normal chakra ui select with {...register}, e.g. whether the field is required or not.

**Comment by manuelpoelzl** [comment]
Nevermind overlook an already existing issue

**Comment by csandman** [comment]
No problem, I've actually been meaning to add guides for using this component with form controllers.  It seems like there's a need for it.

**Comment by manuelpoelzl** [comment]
Your component is a must have for all Chakra UI environments, since Chakra itself does not offer a fully styled select. So a documentation for the integration with react hook form would be absolutely great!

Thanks for such a great component!

**Comment by csandman** [comment]
I got started adding this section to the docs: https://github.com/csandman/chakra-react-select#usage-with-react-form-libraries

There are just so many potential ways to use these libraries, its hard to cover all the bases haha
