### ISSUE TITLE
[FEATURE] Please exported out all Select Interface

### ISSUE THREAD

**Issue by fransiscushermanto** [csandman/chakra-react-select#70]
**Describe the solution you'd like**
I want to create custom component in my project with this chakra-react-select. I need the interface for all Select props so i can make it become a component. I need it as soon as possible. Thanks!

**Comment by csandman** [comment]
These should all be available already!  All of the original interfaces that are available in react select and being exported from this package as well, and I exported the component types in the most recently published version. If you have any questions about what certain interfaces are called, let me know, and I can elaborate tomorrow.

**Comment by csandman** [comment]
You can check out the most recent version notes here: https://github.com/csandman/chakra-react-select/releases/tag/v3.1.1

**Comment by fransiscushermanto** [comment]
@csandman I think it's still to hard, I think it will be as simple as chakra select props. As you can see i need to do exactly the same like what you do to make the interface. Maybe you can simplify the SelectProps?
![image](https://user-images.githubusercontent.com/42550309/158105519-e44482cd-57a8-48e8-9f03-c7826888e47d.png)

**Comment by csandman** [comment]
Sorry, there's not much I can do to change it. All of the interface structures Im using are based on the original structures of react-select. Each of the sub-components are expecting that structure, and it doesn't work if I don't follow it exactly.

**Comment by fransiscushermanto** [comment]
@csandman I see, okay then. Btw i find out that your options that you make need to be GroupedOptions, i think you have make mistake. I think options not always grouped.
![image](https://user-images.githubusercontent.com/42550309/158119900-586cb33c-2c5f-480c-adcd-a288c7cae644.png)

**Comment by fransiscushermanto** [comment]
@csandman Oh i see, okay then.

**Comment by fransiscushermanto** [comment]
@csandman I found out something strange here in your example. I think not all options needed to be grouped ?
![image](https://user-images.githubusercontent.com/42550309/158121151-4f918414-bc30-403a-86d4-1feb44ba3861.png)

**Comment by fransiscushermanto** [comment]
@csandman react-select itself have an example for this 
![image](https://user-images.githubusercontent.com/42550309/158121737-24acd2ce-fb91-45cb-9bb2-80558ba83422.png)

**Comment by csandman** [comment]
And if you need any explanations for the original interfaces with the generics, check out the TypeScript sections of the react-select docs: https://react-select.com/typescript
