### ISSUE TITLE
[QUESTION] Eliminate unnecessary dependencies

### ISSUE THREAD

**Issue by Ruxx28** [csandman/chakra-react-select#78]
I use the package @chakra-ui/react and it contains all the packages that I get the warning message

```
warning " > chakra-react-select@3.1.2" has unmet peer dependency "@chakra-ui/form-control@^1.0.0".        
warning " > chakra-react-select@3.1.2" has unmet peer dependency "@chakra-ui/icon@^2.0.0".
warning " > chakra-react-select@3.1.2" has unmet peer dependency "@chakra-ui/layout@^1.0.0".
warning " > chakra-react-select@3.1.2" has unmet peer dependency "@chakra-ui/menu@^1.0.0".
warning " > chakra-react-select@3.1.2" has unmet peer dependency "@chakra-ui/spinner@^1.0.0".
warning " > chakra-react-select@3.1.2" has unmet peer dependency "@chakra-ui/system@^1.2.0".
```

can you remove them in upcoming updates

**Comment by csandman** [comment]
These dependencies are all required to make chakra-react-select work.  If you have `@chakra-ui/react` installed that should cover them though.  Do you currently have Chakra installed?

**Comment by Ruxx28** [comment]
i have installed chakra before and i see all the components you requested are included in this package except for the icon. I installed your package and got the message that those dependencies are not there yet. not a mistake, i agree that you can use the main package instead of the individual packages

**Comment by csandman** [comment]
What version of the npm cli are you using? `npm --version`

**Comment by Ruxx28** [comment]
yarn v1.22.18
Warning: Prop id did not match.
my solution const AsyncSelect = dynamic<any>( () => import('chakra-react-select').then(e => e.AsyncSelect), { ssr: false } )
[dynamic<any>] Can you suggest any type in any type to help me?
And background property is not available

**Comment by csandman** [comment]
To give a conclusive answer to the start of this post, there is nothing I can do about those installation warnings.

If you have `@chakra-ui/react` installed, then none of the warnings will cause you any errors, and these warnings are exclusive to `yarn`, as `npm` recognizes that all of these packages are installed as dependencies of a sibling dependency of `chakra-react-select`.

**Comment by csandman** [comment]
Scratch my last comment, there is something I can do, and I just did it in [`v3.3.5`](https://github.com/csandman/chakra-react-select/releases/tag/v3.3.5) and ([`v4.0.0-rc.1`](https://github.com/csandman/chakra-react-select/releases/tag/v4.0.0-rc.1) for Chakra v2).  All I had to do was move these packages from `peerDependencies` to `dependencies` which is the same way Chakra has all of their sub packages set up.  If you install either of these versions, you should no longer get any warnings about missing peer deps.

**Comment by coopbri** [comment]
I am encountering this problem with Yarn Berry, but it works fine for me on Yarn Classic. Based on the bugs with Yarn Berry (including hot spots like peer dependency issues), I have an inkling that the issue is with Yarn itself rather than this library. With that being said, I wanted to mention that Yarn Classic is a workaround if someone else has issues on modern versions of Yarn. I haven't tested other tools like `pnpm` (though did try Berry with `pnpm` linker without success).
