### ISSUE TITLE
[BUG] Unable to focus or search using React Production mode.

### ISSUE THREAD

**Issue by JoeVanGundy** [csandman/chakra-react-select#79]
**Describe the bug**
Using the dev build of react, my select component works perfectly.
However, once I go to prod build, the component is unable to be focused and search no longer works.
I went through the dom and the only difference I can find is that on the dev build, the following element exists:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/8807246/162032458-5c044f37-d065-440c-b652-788f1f94b008.png">

All of the other Chakra components works 100% fine, it's just the chakra-react-select component.
Is there any known issue with production builds or minifying?

**To Reproduce**
Can't provide reproduction since it would require a production build.
I'm using create-react-app so really there shouldn't be any weirdness.

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 1.8.7 (but i checked older versions and the issue remains)

**Additional context**
I'm assuming other people aren't having issues with this, but there's no reason that only this library is affected.
The only thing I can think of is some unlisted dependency issue.
Any tips would be greatly appreciated.

**Comment by csandman** [comment]
Can you show me how you implemented the select component?  you can obfuscate variable names but I can't do much without seeing how it's implemented.

The only thing I could guess that it might be without seeing that is if you have custom components defined inside the body of your select component.  If so it should be something like this instead:

```jsx
// Make sure this is defined outside of the component which returns your select
// or you'll run into rendering issues
const customComponents = {
  Option: ({ children, ...props }) => (
    <chakraComponents.Option {...props}>
      {props.data.icon} {children}
    </chakraComponents.Option>
  ),
};

const Example = () => (
  <Select
    name="flavors"
    options={flavorOptions}
    placeholder="Select some flavors..."
    components={customComponents}
  />
);
```

If that's not the case then I'd need to see more about the implementation to have any way to help.

**Comment by JoeVanGundy** [comment]
> 

Sure thing! Have done some more debugging and discovered its stemming from how I'm handling the `ValueContainer`.
Basically I want the select box to say "X items selected" once more than one option has been selected.
Seems that maybe the `child.type.name` value is getting changed in production but not dev.

Is there a better or easier way of handling that?

Here is the code for that:
```
ValueContainer: ({ children, getValue, ...props }) => {

    var values = getValue();
    var valueLabel = '';

    if (values.length === 1) valueLabel = props.selectProps.getOptionLabel(values[0]);
    if (values.length > 1) valueLabel = `${values.length} items selected`;

    // Keep standard placeholder and input from react-select
    var childsToRender = React.Children.toArray(children).filter(
      (child) => ['Input', 'DummyInput', 'Placeholder'].indexOf(child.type.name) >= 0
    );
    return (
      <chakraComponents.ValueContainer {...props}>
        <Box textOverflow="ellipsis" overflow="hidden" whiteSpace="nowrap">
          {!props.selectProps.inputValue && valueLabel}
        </Box>
        {childsToRender}
      </chakraComponents.ValueContainer>
    );
  },
```

**Comment by JoeVanGundy** [comment]
Did some more ready and just went with this implementation in case anyone else encounters it!
Suppose the original issue is that the build is scrubbing the name from the children in ValueContainer. Not sure if that's expected or not, but definitely like this new implementation more.

```
  ValueContainer: ({ children, ...props }) => {
    const { getValue, hasValue } = props;
    const nbValues = getValue().length;
    if (!hasValue) {
      return (
        <chakraComponents.ValueContainer {...props}>{children}</chakraComponents.ValueContainer>
      );
    }
    if (nbValues === 1) {
      return (
        <chakraComponents.ValueContainer {...props}>{children}</chakraComponents.ValueContainer>
      );
    }
    // This dom element is necessary for react-select to function correctly.
    // Without it, focus is all sorts of jank.
    // It's always the second child. So if you have 10 things selected, those 10 are in the first child.
    // Ghost element is the second.
    const necessaryHiddenChild = children && children.length > 0 ? children[1] : false;
    return (
      <chakraComponents.ValueContainer {...props}>
        {`${nbValues} items selected`}
        {necessaryHiddenChild}
      </chakraComponents.ValueContainer>
    );
  },
};
```

**Comment by csandman** [comment]
Ah ok, so I don't really have any experience with the `child.type.name` part of your code, but if I had to guess I'd say it's probably the [`displayName`](https://reactjs.org/docs/react-component.html#displayname) component property.  These are only really meant for debugging purposes as they get obfuscated or removed entirely when you do a production build with `create-react-app`.

It sounds like you solved your issues so I'll close this but if you're still having issues with it feel free to reach out!
